SportNutr.Web/Controllers/AccountController.cs
using System;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using SportNutr.BL;
using SportNutr.Db;
using SportNutr.Domain;

namespace SportNutr.Web.Controllers
{
    public class AccountController : Controller
    {
        private static readonly SportsNutritionDbContext _context = new SportsNutritionDbContext();
        private static readonly EfStoreRepository _repository = new EfStoreRepository(_context);
        private readonly CredentialManager _credentialManager = new CredentialManager(_repository);

        // GET: Display the login page
        public ActionResult Login()
        {
            if (HttpContext.User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        // POST: Process the login form
        [HttpPost]
        public ActionResult Login(string username, string password)
        {
            var client = _credentialManager.ConfirmCredentials(username, password);
            if (client != null)
            {
                AuthenticateUser(client);
                return RedirectToAction("Index", "Home");
            }

            ModelState.AddModelError(string.Empty, "Invalid username or password.");
            return View();
        }

        // GET: Display the registration page
        public ActionResult Register()
        {
            return View();
        }

        // POST: Process the registration form
        [HttpPost]
        public ActionResult Register(string username, string password)
        {
            var client = _credentialManager.EnrollClient(username, password);
            if (client != null)
            {
                AuthenticateUser(client);
                return RedirectToAction("Index", "Home");
            }

            ModelState.AddModelError(string.Empty, "Registration failed. Please try again.");
            return View();
        }

        // Log out the current user and clear session
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            var authCookie = new HttpCookie(FormsAuthentication.FormsCookieName, "")
            {
                Expires = DateTime.Now.AddYears(-1)
            };
            HttpContext.Response.Cookies.Add(authCookie);

            return RedirectToAction("Login");
        }

        // Helper method to authenticate and sign in the user
        private void AuthenticateUser(Client client)
        {
            var ticket = new FormsAuthenticationTicket(
                1, // Ticket version
                client.Username, 
                DateTime.Now,
                DateTime.Now.AddMinutes(20), // Expiration time
                false, // Assuming "Remember me" is not a default option
                client.Privilege, // Using Privilege instead of Role
                "/");

            var encryptedTicket = FormsAuthentication.Encrypt(ticket);
            var authCookie = new HttpCookie(FormsAuthentication.FormsCookieName, encryptedTicket);
            HttpContext.Response.Cookies.Add(authCookie);
        }
    }
}

SportNutr.Web/Controllers/AdminController.cs
using System.Linq;
using System.Web.Mvc;
using SportNutr.Db;
using SportNutr.Web.SecurityItems;

namespace SportNutr.Web.Controllers
{
    [ModeratorAccess]
    public class AdminController : Controller
    {
        private SportsNutritionDbContext db = new SportsNutritionDbContext();

        [HttpGet]
        public ActionResult ViewMembers()
        {
            var members = db.Members.ToList();
            return View(members);
        }

        [HttpPost]
        public ActionResult ApproveMember(int id)
        {
            var member = db.Members.Find(id);
            if (member != null)
            {
                // Если нужно выполнить какие-то действия при одобрении, можно сделать это здесь
                db.SaveChanges();
            }
            return RedirectToAction("ViewMembers");
        }

        [HttpPost]
        public ActionResult DisapproveMember(int id)
        {
            var member = db.Members.Find(id);
            if (member != null)
            {
                db.Members.Remove(member);
                db.SaveChanges();
            }
            return RedirectToAction("ViewMembers");
        }
    }

}

SportNutr.Web/Controllers/HomeController.cs
using System.Web.Mvc;

namespace SportNutr.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";
            return View();
        }
        
        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";
            return View();
        }
    }
}

SportNutr.Web/Controllers/MemberController.cs
using System.Web.Mvc;
using SportNutr.Db;
using SportNutr.Domain;

namespace SportNutr.Web.Controllers
{
    public class MemberController : Controller
    {
        private SportsNutritionDbContext db = new SportsNutritionDbContext();

        [HttpGet]
        public ActionResult BecomeMember()
        {
            return View();
        }

        [HttpPost]
        public ActionResult BecomeMember(Member member)
        {
            if (ModelState.IsValid)
            {
                db.Members.Add(member);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            return View(member);
        }

        public ActionResult ThankYou()
        {
            return View();
        }
    }

}

SportNutr.Web/Views/Admin/ViewMembers.cshtml
@model System.Collections.Generic.List<SportNutr.Domain.Member>

@{
ViewBag.Title = "View Members";
Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="content-wrapper">
    <h2 class="mb-4">View Members</h2>

    <table class="table table-striped">
        <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.First().FirstName)</th>
            <th>@Html.DisplayNameFor(model => model.First().LastName)</th>
            <th>@Html.DisplayNameFor(model => model.First().Email)</th>
            <th>@Html.DisplayNameFor(model => model.First().DateOfBirth)</th>
            <th>@Html.DisplayNameFor(model => model.First().Gender)</th>
            <th>@Html.DisplayNameFor(model => model.First().FavoriteSport)</th>
            <th>@Html.DisplayNameFor(model => model.First().Goals)</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>@Html.DisplayFor(modelItem => item.FirstName)</td>
            <td>@Html.DisplayFor(modelItem => item.LastName)</td>
            <td>@Html.DisplayFor(modelItem => item.Email)</td>
            <td>@Html.DisplayFor(modelItem => item.DateOfBirth)</td>
            <td>@Html.DisplayFor(modelItem => item.Gender)</td>
            <td>@Html.DisplayFor(modelItem => item.FavoriteSport)</td>
            <td>@Html.DisplayFor(modelItem => item.Goals)</td>
            <td>
                @using (Html.BeginForm("ApproveMember", "Admin", FormMethod.Post))
                {
                @Html.AntiForgeryToken()
                @Html.Hidden("id", item.Id)
                <button type="submit" class="btn btn-success btn-sm">Approve</button>
                }
                @using (Html.BeginForm("DisapproveMember", "Admin", FormMethod.Post))
                {
                @Html.AntiForgeryToken()
                @Html.Hidden("id", item.Id)
                <button type="submit" class="btn btn-danger btn-sm">Disapprove</button>
                }
            </td>
        </tr>
        }
        </tbody>
    </table>
</div>

SportNutr.Web/Views/Member/BecomeMember.cshtml
@model SportNutr.Domain.Member

@{
    ViewBag.Title = "Become a Member";
    Layout = "../Shared/_Layout.cshtml";
}

<h2>Become a Member</h2>

@using (Html.BeginForm())
{
@Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Member</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.FavoriteSport, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FavoriteSport, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FavoriteSport, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Goals, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Goals, new { @class = "form-control", rows = 4 })
            @Html.ValidationMessageFor(model => model.Goals, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Submit" class="btn btn-default" />
        </div>
    </div>
</div>
}

SportNutr.Web/Views/Member/ThankYou.cshtml
@model dynamic

@{
    ViewBag.Title = "Thank You";
    Layout = "../Shared/_Layout.cshtml";
}

<h2>Thank You for Becoming a Member!</h2>
<p>We appreciate your interest in our store.</p>

SportNutr.Web/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Admin Panel</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-MzxrJeLrXQllpR4hX7vZKP4Xwi6x5t2bN5rBNg6mrq1YPrs46XzVfP5hsaeXt2E" crossorigin="anonymous">
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            display: flex;
            flex-direction: column;
            height: 100vh;
            background-color: #1c1c1c;
            color: #f8f9fa;
        }
        .navbar {
            background-color: #343a40;
            padding: 10px 20px;
            display: flex;
            justify-content: space-between;
            align-items: center;
            border-bottom: 1px solid #e0e0e0;
        }
        .navbar a {
            color: #f8f9fa;
            text-decoration: none;
            margin-left: 15px;
        }
        .main-container {
            display: flex;
            flex: 1;
        }
        .sidebar {
            width: 250px;
            background-color: #2c2c2c;
            padding: 15px;
            border-right: 1px solid #e0e0e0;
        }
        .sidebar h4 {
            margin-top: 0;
            color: #f8f9fa;
        }
        .sidebar a {
            color: #f8f9fa;
            text-decoration: none;
            display: block;
            margin-bottom: 10px;
        }
        .sidebar a:hover {
            color: #007bff;
        }
        .content-wrapper {
            flex: 1;
            padding: 20px;
            background-color: #1c1c1c;
        }
        .table {
            width: 100%;
            border-collapse: collapse;
            color: #f8f9fa;
        }
        .table th, .table td {
            border: 1px solid #555;
            padding: 10px;
            text-align: left;
        }
        .table th {
            background-color: #343a40;
        }
        .table-striped tbody tr:nth-of-type(odd) {
            background-color: #2c2c2c;
        }
        .btn {
            padding: 5px 10px;
            color: #fff;
            text-decoration: none;
            border-radius: 5px;
        }
        .btn-success {
            background-color: #28a745;
        }
        .btn-danger {
            background-color: #dc3545;
        }
        .navbar-brand {
            color: #f8f9fa;
            text-decoration: none;
            font-size: 1.5rem;
        }
    </style>
</head>
<body>
<nav class="navbar">
    <div>
        <a class="navbar-brand" href="#">Admin Panel</a>
    </div>
    <div>
        <a href="@Url.Action("Index", "Home")">Home</a>
        <a href="@Url.Action("Logout", "Account")">Logout</a>
    </div>
</nav>
<div class="main-container">
    <div class="sidebar">
        <h4>Navigation</h4>
        
        <a href="@Url.Action("ViewMembers", "Admin")">View Members</a>
        
    </div>
    <div class="content-wrapper">
        @RenderBody()
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js" integrity="sha384-LtrjvnR4Twt/qOuYxE721u19sVFLVSA4hf/rRt6PrZTmiPltdZcI7q7PXQBYTKyf" crossorigin="anonymous"></script>
<script>
    $(function() {
        $('[data-toggle="tooltip"]').tooltip()
    });
</script>
</body>
</html>

SportNutr.Web/Views/Shared/_AuthLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Sport Nutrition Store</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        body {
            background: #1c1c1c;
            display: flex;
            flex-direction: column;
            min-height: 100vh;
            color: #f8f9fa;
        }
        .navbar {
            margin-bottom: 20px;
            background-color: #343a40;
        }
        .navbar-brand, .nav-link {
            color: #f8f9fa !important;
        }
        .content-wrapper {
            flex: 1;
            display: flex;
            justify-content: center;
            align-items: center;
            padding: 20px;
        }
        .form-signin, .form-signup {
            max-width: 500px;
            padding: 30px;
            background: #2c2c2c;
            border-radius: 1rem;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }
        .form-signin h2, .form-signup h2 {
            margin-bottom: 30px;
            color: #f8f9fa;
        }
        .form-group label {
            color: #f8f9fa;
        }
        .form-control {
            background-color: #3a3a3a;
            border: 1px solid #555;
            color: #f8f9fa;
        }
        .form-control::placeholder {
            color: #bbb;
        }
        .form-control:focus {
            background-color: #3a3a3a;
            color: #f8f9fa;
            border-color: #007bff;
        }
        .btn-primary {
            background-color: #007bff;
            border-color: #007bff;
        }
        .btn-success {
            background-color: #28a745;
            border-color: #28a745;
        }
        .form-signin .register-link, .form-signup .login-link {
            margin-top: 10px;
            color: #f8f9fa;
        }
        .logo {
            display: flex;
            justify-content: center;
            margin-bottom: 20px;
        }
        .logo img {
            max-width: 150px;
        }
    </style>
</head>
<body>
<nav class="navbar navbar-expand-lg">
    <a class="navbar-brand" href="#">Sport Nutrition Store</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                @Html.ActionLink("Home", "Index", "Home", null, new { @class = "nav-link" })
            </li>
            <li class="nav-item">
                @Html.ActionLink("About", "About", "Home", null, new { @class = "nav-link" })
            </li>
            <li class="nav-item">
                @Html.ActionLink("Contact", "Contact", "Home", null, new { @class = "nav-link" })
            </li>
            @if (!User.Identity.IsAuthenticated)
            {
            <li class="nav-item">
                @Html.ActionLink("Login", "Login", "Account", null, new { @class = "nav-link" })
            </li>
            <li class="nav-item">
                @Html.ActionLink("Register", "Register", "Account", null, new { @class = "nav-link" })
            </li>
            }
            else
            {
            if (User.IsInRole("Moderator"))
            {
            <li class="nav-item">
                @Html.ActionLink("View Members", "ViewMembers", "Admin", null, new { @class = "nav-link" })
            </li>
            }
            <li class="nav-item">
                @Html.ActionLink("Logout", "Logout", "Account", null, new { @class = "nav-link" })
            </li>
            }
        </ul>
    </div>
</nav>
<div class="content-wrapper">
    @RenderBody()
</div>

<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
<script>
    $(function() {
        $('[data-toggle="tooltip"]').tooltip()
    });
</script>
</body>
</html>

SportNutr.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link rel="stylesheet" href="~/Content/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/Content/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/Content/css/slicknav.css">
    <link rel="stylesheet" href="~/Content/css/flaticon.css">
    <link rel="stylesheet" href="~/Content/css/gijgo.css">
    <link rel="stylesheet" href="~/Content/css/animate.min.css">
    <link rel="stylesheet" href="~/Content/css/animated-headline.css">
    <link rel="stylesheet" href="~/Content/css/magnific-popup.css">
    <link rel="stylesheet" href="~/Content/css/fontawesome-all.min.css">
    <link rel="stylesheet" href="~/Content/css/themify-icons.css">
    <link rel="stylesheet" href="~/Content/css/slick.css">
    <link rel="stylesheet" href="~/Content/css/nice-select.css">
    <link rel="stylesheet" href="~/Content/css/style.css">
</head>
<body>
<!-- ? Preloader Start -->
<div id="preloader-active">
    <div class="preloader d-flex align-items-center justify-content-center">
        <div class="preloader-inner position-relative">
            <div class="preloader-circle"></div>
            <div class="preloader-img pere-text">
                <img src="~/Content/img/logo/loder.png" alt="">
            </div>
        </div>
    </div>
</div>
<!-- Preloader Start -->
<header>
    <!--? Header Start -->
    <div class="header-area header-transparent">
        <div class="main-header header-sticky">
            <div class="container-fluid">
                <div class="row align-items-center">
                    <!-- Logo -->
                    <div class="col-xl-2 col-lg-2 col-md-1">
                        <div class="logo">
                            <a href="index.html"><img src="~/Content/img/logo/logo.png" alt=""></a>
                        </div>
                    </div>
                    <div class="col-xl-10 col-lg-10 col-md-10">
                        <div class="menu-main d-flex align-items-center justify-content-end">
                            <!-- Main-menu -->
                            <div class="main-menu f-right d-none d-lg-block">
                                <nav>
                                    <ul id="navigation">
                                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                                        <li>@Html.ActionLink("About", "About", "Home")</li>
                                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                                        @if (!User.Identity.IsAuthenticated)
                                        {
                                            <li>@Html.ActionLink("Login", "Login", "Account", new { area = "" }, new { @class = "nav-link" })</li>
                                            <li>@Html.ActionLink("Register", "Register", "Account", new { area = "" }, new { @class = "nav-link" })</li>
                                        }
                                        else
                                        {
                                            if (User.IsInRole("Moderator"))
                                            {
                                                <li>@Html.ActionLink("View Members", "ViewMembers", "Admin")</li>
                                            }
                                            <li>@Html.ActionLink("Logout", "Logout", "Account", new { area = "" }, new { @class = "nav-link" })</li>
                                        }

                                    </ul>
                                </nav>
                            </div>
                            <div class="header-right-btn f-right d-none d-lg-block ml-30">
                                <a href="@Url.Action("BecomeMember", "Member")" class="btn header-btn">became a member</a>
                            </div>
                        </div>
                    </div>   
                    <!-- Mobile Menu -->
                    <div class="col-12">
                        <div class="mobile_menu d-block d-lg-none"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->
</header>
@RenderBody()
<footer>
    <!--? Footer Start-->
    <div class="footer-area section-bg" data-background="assets/img/gallery/section_bg03.png">
        <div class="container">
            <div class="footer-top footer-padding">
                <!-- Footer Menu -->
                <div class="row d-flex justify-content-between">
                    <div class="col-xl-2 col-lg-2 col-md-4 col-sm-6">
                        <div class="single-footer-caption mb-50">
                            <div class="footer-tittle">
                                <h4>COMPANY</h4>
                                <ul>
                                    <li><a href="#">About Us</a></li>
                                    <li><a href="#">Company</a></li>
                                    <li><a href="#"> Press & Blog</a></li>
                                    <li><a href="#"> Privacy Policy</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-3 col-md-4 col-sm-6">
                        <div class="single-footer-caption mb-50">
                            <div class="footer-tittle">
                                <h4>Open hour</h4>
                                <ul>
                                    <li><a href="#">Monday 11am-7pm</a></li>
                                    <li><a href="#"> Tuesday-Friday 11am-8pm</a></li>
                                    <li><a href="#"> Saturday 10am-6pm</a></li>
                                    <li><a href="#"> Sunday 11am-6pm</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-2 col-lg-3 col-md-4 col-sm-6">
                        <div class="single-footer-caption mb-50">
                            <div class="footer-tittle">
                                <h4>RESOURCES</h4>
                                <ul>
                                    <li><a href="#">Home Insurance</a></li>
                                    <li><a href="#">Travel Insurance</a></li>
                                    <li><a href="#"> Car Insurance</a></li>
                                    <li><a href="#"> Business Insurance</a></li>
                                    <li><a href="#"> Heal Insurance</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-4 col-md-5 col-sm-6">
                        <div class="single-footer-caption mb-50">
                            <!-- logo -->
                            <div class="footer-logo">
                                <a href="index.html"><img src="~/Content/img/logo/logo2_footer.png" alt=""></a>
                            </div>
                            <div class="footer-tittle">
                                <div class="footer-pera">
                                    <p class="info1">GThe trade war currently ensuing between te US anfd several natxions around thdhe globe, most fiercely with.</p>
                                </div>
                            </div>
                            <!-- Footer Social -->
                            <div class="footer-social ">
                                <a href="https://www.facebook.com/sai4ull"><i class="fab fa-facebook-f"></i></a>
                                <a href=""><i class="fab fa-twitter"></i></a>
                                <a href="#"><i class="fas fa-globe"></i></a>
                                <a href="#"><i class="fab fa-instagram"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Footer Bottom -->
            <div class="footer-bottom">
                <div class="row d-flex align-items-center">
                    <div class="col-lg-12">
                        <div class="footer-copy-right text-center">
                            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                                Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer End-->
</footer>
<!-- Scroll Up -->
<div id="back-top" >
    <a title="Go to Top" href="#"> <i class="fas fa-level-up-alt"></i></a>
</div>
    
@Scripts.Render("~/bundles/mainjs")
</body>
</html>


<style>
    .header-area {
        padding-bottom: 20px; /* увеличиваем отступ снизу */
    }
    .content-wrapper {
        padding-top: 60px; /* добавляем отступ сверху */
    }
</style>